[mypy]
ignore_missing_imports = True
warn_return_any = False
warn_unused_configs = True
no_implicit_optional = False
disable_error_code = annotation-unchecked

[mypy-pipeline]
disable_error_code = attr-defined, operator, index

[mypy-attack]
disable_error_code = arg-type, call-overload, assignment

[mypy-figures]
disable_error_code = type-var, index, arg-type, assignment

[mypy-run]
disable_error_code = arg-type
